### ISSUE TITLE
D2k - Add d2k.pal

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/ArtSrc#6]
There used to be a d2k.pal in d2k bits long time ago, which is basically d2k's PALETTE.BIN but in the format CnC games use. OpenRA can read the .BIN file, but d2k.pal is required to work on stuff like SHP Builder. It doesn't seem like i have it on this PC, would be nice to keep it here.

**Comment by pchote** [comment]
The format/data is identical (it is just the VGA palette register).  You can rename it to .pal locally if other programs aren't smart enough to use it with its default name.

**Comment by MustaphaTR** [comment]
Seems so, this is not really required then.
